Realice el Header de la pagina
NikaoV/Hoteles pull request #1
Opened 2023-07-28 05:53 UTC by NikaoV

2023-07-28 21:53 UTC, DanielCalleCO commented
Pregunta... 

![image](https://github.com/NikaoV/Hoteles/assets/100431019/3444c196-d909-4089-b935-f6dee21d2579)

Esta parte de abajo, por qué la colocaste? no se me hace sentido... y si puedes, coloca las fechas entre los dos textos luego del título... la idea del texto de abajo ("All sizes hotels of all category prices, in all countries") es que muestre la info que los filtros están filtrando, pero eso lo hacemos al final.

2023-07-28 21:55 UTC, DanielCalleCO requested changes
Por ahora está bien... siento que el contraste del fondo es muy fuerte vs las letras en blanco, pero si para ti está bien, no hay problema por mí hermano!

Revisa el comentario que te dejé y dale orden al texto

2023-07-28 22:12 UTC, NikaoV commented
Si señor

2023-07-31 23:43 UTC, DanielCalleCO approved these changes

2023-08-01 11:27 UTC, merged